# This is a basic workflow to help you get started with Actions

name: shadymofo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEbXohFtqQngCsIRCLsztfIyxicekFAlzdq+oACgkQsztfIyxi
cel17Q//cNLOz19GMcE5PEJ3fjALOPHLspbh/pCj7ekMJozMJK+hX1ahR5m/yDPM
UcxEnek1d95Yjp8puixuefucR+BGCQP0t3Sya6hY/Mobp9PteoR/wL72svbuO+zB
tZ3mhqRsI+onr65Gvp35P2gOTjHWcmo4/n/AIJPmHWGT046BXzOn/bedVmBXxdSq
OjMgZS/dkrHDqwqjzC0nC4QC6G7JIGr4JC3p9PQjWKc8IXkqjjK33Y8sawJkvpD0
xcRsNNJA4s/64nil/XRK+Vy2TrleUHFV7YxL5gOvBhmg3HOn0hX+C5L2ItWh2RR0
sPk4A/SK3vcVDwrGdSRXX4ePZHBpfyhBw0yPVsFuIQtWtr1BfBnGcVz14gVbzeOs
pOmQETbqMwOk0Q51xdE84M7dnUvpDNZsi2/Wf5qSOpHcBQ2RhDY+Wzs4CD6Hzt4U
dmrWaHWG3O4vdvAeTHErvE/AHdY2SC1Y3OKRtqpUUKKJ7Q+X42ZPiH4YwpYeZMl2
7nYpWiZJh8AguqyYlU0Gjb+gTFOWjRljM/5Z+ujcPx7jmKcMcE+qJHCA2Ykaopb2
049RKvLgKKq1jOrITzupzQOK/CV3Ml5ufYZhHfgfKewDMYi+f9MBeBgoJ67FYHJ2
Xl/SBMWj8GIZ9E00b4XukG68pUtJbTfkJnhRDqA1itz/v+SS77o=
=vtnk
-----END PGP SIGNATURE-----

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
